version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  user-keycloak:
    container_name: user-keycloak
    image: quay.io/keycloak/keycloak:17.0.1
    ports:
      - 8080:8080
    env_file:
      - .env
    command: start-dev
    depends_on:
      - postgres

  user-app:
    container_name: user-app
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - user-keycloak
    ports:
      - 8000:5000
